name: Static Web App Build CI

on:
  push:
    branches:
      - framework16*
  repository_dispatch:
    types: [definition_update]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Upload Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - name: Build and tar
        run: |
          npm run build:azure
          tar caf framework_via_app.tar.gz dist/
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: framework_via_app.tar.gz
